//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntytiFrame.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class DriveEntities : DbContext
    {
        public DriveEntities()
            : base("name=DriveEntities")
        {
            Database.SetInitializer(
                new DropCreateDatabaseIfModelChanges<DriveEntities>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Client>()
                .Property(e => e.ClientName)
                .IsUnicode(false);

            modelBuilder.Entity<Client>()
                .Property(e => e.ClientAdress)
                .IsUnicode(false);

            //modelBuilder.Entity<Client>()
            //    .Property(e => e.ClientNumber)
            //    .IsUnicode(false);

        }

        public virtual DbSet<Client> Client { get; set; }
    }
}
